editor: source

execute:
  cache: false # "Danger Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: >
  A Reproducible R Pipeline for Processing DATASUS Annual Population Estimates
  by Municipality, Age, and Sex in Brazil (2000-2024)
author: "Daniel Vartanian & Aline Martins de Carvalho"
keyword: >
  pipelines, population estimates, data munging, data science, rstats,
  open data, open science, datasus, ibge, brazil
date: today
date-format: "YYYY-MM-DD"

website:
  favicon: images/sustentarea-icon.svg
  site-url: https://sustentarea.github.io/datasus-pop-estimates/
  repo-url: https://github.com/sustentarea/datasus-pop-estimates/
  issue-url: https://github.com/sustentarea/datasus-pop-estimates/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main
  repo-actions: [edit, source, issue]
  search: false
  navbar:
    title: false
    background: "#272B33"
    right:
      - icon: github
        href: https://github.com/sustentarea/datasus-pop-estimates/
        aria-label: GitHub

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    locale: en
    language: en-us
    code-fold: true
    code-link: true
    code-tools: false
    df-print: paged
    fig-align: center
    cap-location: top
    lightbox: true
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/styles.scss, brand]
    other-links:
      - text: Sustentarea website
        href: https://www.fsp.usp.br/sustentarea

google-scholar: true
bibliography: references.bib
